# Generated by Django 5.2.8 on 2025-11-24 02:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CableLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Номер кабельной линии')),
                ('cable_brand', models.CharField(max_length=255, verbose_name='Марка кабеля')),
                ('start_muff', models.CharField(max_length=255, verbose_name='Марка концевой муфты в начале')),
                ('end_muff', models.CharField(max_length=255, verbose_name='Марка концевой муфты в конце')),
                ('connect_muff_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='1-я соединительная муфта')),
                ('connect_muff_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='2-я соединительная муфта')),
                ('connect_muff_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='3-я соединительная муфта')),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Длина кабеля (м)')),
                ('core_count', models.PositiveIntegerField(verbose_name='Количество жил')),
                ('commissioning_date', models.DateField(verbose_name='Дата ввода в эксплуатацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Кабельная линия',
                'verbose_name_plural': 'Кабельные линии',
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название предприятия')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Предприятие',
                'verbose_name_plural': 'Предприятия',
            },
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_date', models.DateTimeField(verbose_name='Дата и время аварии')),
                ('accident_type', models.CharField(choices=[('short_circuit', 'Короткое замыкание'), ('break', 'Обрыв'), ('insulation_breakdown', 'Пробой изоляции на муфте'), ('other', 'Другое')], max_length=50, verbose_name='Тип аварии')),
                ('description', models.TextField(verbose_name='Описание аварии')),
                ('downtime', models.DurationField(blank=True, null=True, verbose_name='Время простоя')),
                ('cable_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cable_manager.cableline', verbose_name='Кабельная линия')),
            ],
            options={
                'verbose_name': 'Авария',
                'verbose_name_plural': 'Аварии',
            },
        ),
        migrations.AddField(
            model_name='cableline',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cable_manager.enterprise', verbose_name='Предприятие'),
        ),
        migrations.CreateModel(
            name='HighVoltageTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(verbose_name='Дата испытания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('test_voltage', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Испытательное напряжение (кВ)')),
                ('insulation_resistance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Сопротивление изоляции (МОм)')),
                ('cable_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cable_manager.cableline', verbose_name='Кабельная линия')),
            ],
            options={
                'verbose_name': 'Высоковольтное испытание',
                'verbose_name_plural': 'Высоковольтные испытания',
            },
        ),
        migrations.CreateModel(
            name='MuffChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_muff_type', models.CharField(choices=[('start', 'Начальная концевая'), ('end', 'Конечная концевая'), ('conn1', 'Соединительная 1'), ('conn2', 'Соединительная 2'), ('conn3', 'Соединительная 3')], max_length=50, verbose_name='Тип измененной муфты')),
                ('old_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Старое значение')),
                ('new_value', models.CharField(max_length=255, verbose_name='Новое значение')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('cable_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cable_manager.cableline', verbose_name='Кабельная линия')),
            ],
            options={
                'verbose_name': 'История изменений муфт',
                'verbose_name_plural': 'История изменений муфт',
            },
        ),
        migrations.CreateModel(
            name='PDDMeasurementSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(verbose_name='Дата измерений')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания к серии измерений')),
                ('cable_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cable_manager.cableline', verbose_name='Кабельная линия')),
            ],
            options={
                'verbose_name': 'Сессия измерений ЧР',
                'verbose_name_plural': 'Сессии измерений ЧР',
            },
        ),
        migrations.CreateModel(
            name='SinglePDMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage_level', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Уровень напряжения (кВ)')),
                ('core_1_discharge', models.FloatField(blank=True, null=True, verbose_name='ЧР на жиле 1 (пКл)')),
                ('core_1_distance', models.FloatField(blank=True, null=True, verbose_name='Расстояние ЧР на жиле 1 (м)')),
                ('core_2_discharge', models.FloatField(blank=True, null=True, verbose_name='ЧР на жиле 2 (пКл)')),
                ('core_2_distance', models.FloatField(blank=True, null=True, verbose_name='Расстояние ЧР на жиле 2 (м)')),
                ('core_3_discharge', models.FloatField(blank=True, null=True, verbose_name='ЧР на жиле 3 (пКл)')),
                ('core_3_distance', models.FloatField(blank=True, null=True, verbose_name='Расстояние ЧР на жиле 3 (м)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cable_manager.pddmeasurementsession', verbose_name='Сессия измерений')),
            ],
            options={
                'verbose_name': 'Измерение ЧР при напряжении',
                'verbose_name_plural': 'Измерения ЧР при напряжениях',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cable_manager.enterprise', verbose_name='Предприятие')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
